### ISSUE TITLE
Simulation input not taking two separate sky inputs 

### ISSUE THREAD

**Issue by aishrimc** [OxfordSKA/OSKAR#25] opened 2020-05-16 06:53 UTC
Hello,
While running a simulation with oskarpy using a python script, the simulation is taking only one sky model. The inputs are given as :
`sim.set_sky_model('point_source.osm')`
`sim.set_sky_model('diffuse_source.fits')`
It is taking only the 2nd one, i.e. `sim.set_sky_model('diffuse_source.fits')`. I tried switching places to see if there is something wrong with the input file, but as it turned out it is only taking whatever is the last `sim.set_sky_mode`. What is the way in which I can input both?

**Comment by fdulwich** [comment] 2020-05-17 21:43
It is only possible to set a single sky model, so this is the correct behaviour. If you want to combine two (or more) sky models into one beforehand though, you should use the `append()` method on the sky model itself before calling `set_sky_model()`.

**Comment by aishrimc** [comment] 2020-06-12 18:05
Hi, 
Just another small query. For 2 sky models A and B, should the append go like:
`sky_A = oskar.Sky.from_fits_file(A.fits)`
`sky_B = oskar.Sky.load(B.osm)`
`sky = sky_A`
`sky.append(sky_B)`
`sim = oskar.Interferometer(settings=settings)`
`sim.set_sky_model(sky)`

**Comment by fdulwich** [comment] 2020-06-12 19:09
After loading them both, you can just do `sky_A.append(sky_B)` to append B to A, and then `sim.set_sky_model(sky_A)` (there should be no need to copy).

**Comment by aishrimc** [comment] 2020-06-16 06:53
Hello,
So I did as you suggested and I found the following problems:
1. B.osm contains sources with fluxes as high as 1.5Jy but if the simulation is done using just B.osm the brightest point in the image (obtained using CASA) is ~10^(-5) Jy/beam. 
2. A.fits is actually a diffuse image cube and the brightest pixel in this is ~10^(-5)Jy/pixel. The reconstructed image after doing the simulation gives the highest flux is ~10(-3) Jy/beam. Is it because of the fact that the fits cube is diffuse?
3. On combining A.fits and B.osm (as suggested above), the resultant image has A as the dominant component with the point sources hardly showing.
Can you suggest why the above are happening?

**Comment by fdulwich** [comment] 2020-06-18 01:17
You might want to think about how the sources (or pixels) interact with both the station beams and the synthesized beam. I can't comment on your results specifically as I don't know the details of your inputs, but it might be worth checking whether the bright sources in your sky model B are either resolved, or are too far from the phase centre (in which case there could be many reasons why their apparent amplitudes are smaller than expected - I'm guessing beam attenuation, smearing, or image reconstruction errors - check if any of these apply here). Check as well if using a steep spectral index and the source fluxes are defined at a reference frequency far from the observation frequency.

Also if using a FITS image as a sky model, be aware that each pixel is treated as a compact source. If there are many compact sources very close to each other which cannot be resolved by the interferometer, then they will appear as a single brighter source after imaging. (This is what Jy/beam really means if you think about it.)

**Comment by aishrimc** [comment] 2020-06-19 18:15
Hi, 
So as you suggested I have done the flux scaling to the observed frequency and then on running the simulation with only B.osm I am recovering the correct fluxes. However on combining A.fits with B.osm it appears that the fits is overriding the sky model text file, since even with a text file input of maximum 1.0 Jy and fits with ~10^(-5)Jy/pixel the recovered fluxes is ~10^(-3) Jy which is the same as obtained with a simulation having only A.fits as the input sky model.

**Comment by fdulwich** [comment] 2020-06-28 21:18
I haven't been able to reproduce this problem in my own tests. I loaded a FITS image of an extended source as `sky_A` and generated a source grid as `sky_B`, and combined them using `sky_B.append(sky_A)`. After a call to `set_sky_model(sky_B)` I was able to run a simulation which clearly showed that both sky model components had been used. The attached image shows the effects of using both sky models separately (left & middle panels) and combined (right panel) - everything appears as expected, also if I use `sky_A.append(sky_B)` and then `set_sky_model(sky_A)`.

![two_separate_sky_inputs](https://user-images.githubusercontent.com/145223/85958392-23c71b80-b98d-11ea-91ba-c5443fdd712b.png)

**Comment by parphyam** [comment] 2020-06-29 13:03
Hi, 
So as  I can see from your images, your point sources are well separated. When I tried with one source at the phase centre with the diffuse emission, I got back the bright image at the phase centre with the diffuse emission in the background. With only diffuse emission I got back the smoothed out version (since the the telescope is unable to resolve each pixel of the diffuse image). However usage of a number of (almost 2600) closely spaced (w.r.t. the resolution) point sources together with the diffuse emission, the simulator is unable to recover the point sources, even the ones quite far apart. I am attaching the images for your reference. 

![diffuse_source_only](https://user-images.githubusercontent.com/55325472/86008865-06e72280-ba37-11ea-933e-db9b27aa227e.png)
![2600_point_and_diffuse](https://user-images.githubusercontent.com/55325472/86008872-0c446d00-ba37-11ea-818f-924fd325fd0f.png)

**Comment by aishrimc** [comment] 2020-06-29 13:09
Hi, 
So as  I can see from your images, your point sources are well separated. When I tried with one source at the phase centre with the diffuse emission, I got back the source at the phase centre with the diffuse emission in the background. With only diffuse emission I got back the smoothed out version (since the the telescope is unable to resolve each pixel of the diffuse image) of the emission which nevertheless showed the expected fluctuations. However usage of a large number of (2621) closely spaced (w.r.t. the resolution) point sources together with the diffuse emission, the simulator is unable to recover the point sources, even the ones quite far apart. I am attaching the images for your reference. 
![2600_point_and_diffuse](https://user-images.githubusercontent.com/39078247/86009235-9a205800-ba37-11ea-98c3-803d9bcd7e15.png)
![point_source_single](https://user-images.githubusercontent.com/39078247/86009122-7230f480-ba37-11ea-8717-8744ee83743e.png)
![diffuse_source_only](https://user-images.githubusercontent.com/39078247/86009152-7bba5c80-ba37-11ea-90ae-38aa951be9fe.png)

**Comment by fdulwich** [comment] 2020-06-29 17:06
To understand the results you're seeing, I suggest doing a systematic study to change the separation of the point sources in the field relative to the telescope resolution (you can increase the effective source separation the easy way by increasing the observation frequency, though you will also need to change the image sampling to match), until they start to become resolved - this may help to explain what's going on.

> However usage of a large number of (2621) closely spaced (w.r.t. the resolution) point sources together with the diffuse emission, the simulator is unable to recover the point sources, even the ones quite far apart.

This isn't a very precise description but I'll make a guess about what could be happening based on the width of the PSF in the image, the number of sources, the size of your field and your TEST_2 image. Try the test above, bearing in mind that the sidelobes of the dirty beam have considerable structure at large distances (and can also be negative). Also think about what an interferometer is able to measure given a large, uniformly flat source.

I'll close this issue now, as I don't believe it's related to OSKAR not being able to use two separate sky inputs.

**Closed by fdulwich** 2020-06-29 17:06 UTC
